language: cpp
sudo: false
dist: trusty
compiler:
- clang

#necessary to get an up to date standard library
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

script:
- mkdir -p build
- cd build
- c++ -v
- cmake .. -DCMAKE_BUILD_TYPE=Release
- cmake --build .
- ctest --output-on-failure .


